name: Run Scraper Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Every hour (UTC)
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install certifi pymongo[srv] pandas

    - name: Verify MongoDB connection
      run: |
        python -c "
        from pymongo import MongoClient
        import certifi
        try:
            client = MongoClient(
                'mongodb+srv://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASSWORD }}@books.kustpvh.mongodb.net/?retryWrites=true&w=majority&appName=books',
                tlsCAFile=certifi.where(),
                serverSelectionTimeoutMS=5000
            )
            client.server_info()
            print('✅ MongoDB connection successful')
        except Exception as e:
            print(f'❌ MongoDB connection failed: {e}')
            raise
        "

    - name: Run scraper
      run: python main.py
      timeout-minutes: 15

    - name: Upload CSV artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: book-data
        path: data/book_details.csv